# Generated by Django 5.2.1 on 2025-07-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadojuego',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
