# Generated by Django 5.2.4 on 2025-07-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_estadojuego_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadojuego',
            name='intentos',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='estadojuego',
            name='nivel',
            field=models.CharField(default='basico', max_length=10),
        ),
    ]
