# Generated by Django 5.2.4 on 2025-08-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_estadojuego_intentos_estadojuego_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadojuego',
            name='intentos',
        ),
        migrations.AddField(
            model_name='estadojuego',
            name='intentos_restantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadojuego',
            name='nivel',
            field=models.CharField(default='', max_length=20),
        ),
    ]
