# Generated by Django 5.2.4 on 2025-08-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0004_remove_estadojuego_intentos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadojuego',
            old_name='intentos_restantes',
            new_name='intentos',
        ),
        migrations.RemoveField(
            model_name='estadojuego',
            name='nivel',
        ),
        migrations.AlterField(
            model_name='estadojuego',
            name='estado',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
