# Generated by Django 5.2.4 on 2025-08-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0005_rename_intentos_restantes_estadojuego_intentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadojuego',
            name='nivel',
            field=models.CharField(default='basico', max_length=20),
        ),
        migrations.AlterField(
            model_name='estadojuego',
            name='estado',
            field=models.JSONField(default=list),
        ),
    ]
