# Generated by Django 5.2.4 on 2025-08-03 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0006_estadojuego_nivel_alter_estadojuego_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_victorias', models.PositiveIntegerField(default=0)),
                ('total_derrotas', models.PositiveIntegerField(default=0)),
                ('partidas_jugadas', models.PositiveIntegerField(default=0)),
                ('tiempo_total_segundos', models.PositiveIntegerField(default=0)),
                ('nivel_mas_jugado', models.CharField(blank=True, max_length=10, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
